### ISSUE TITLE
README.md csapattagok

### ISSUE THREAD

**Issue by poczemartin** [poczemartin/Git-projekt2#1]
README.md állományba a csapattagok beírása

**Comment by majorbalintistvan** [comment]
Rendben Főni küldöm a csapatot

**Comment by poczemartin** [comment]
gyorsan gyorsan

**Comment by majorbalintistvan** [comment]
Bogárraj! ismétlem Bogárraj közeledik!
 Készüljetek!

**Comment by majorbalintistvan** [comment]
Jó hír. A radar nem jelez többet már. folytassátok a munkát.
